CREATE TABLE CLIENTES (
CODIGO INT IDENTITY(1,1) NOT NULL, 
NOME VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NULL,
CPF VARCHAR(15) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO));
GO

CREATE TABLE PRODUTOS (
CODIGO INT IDENTITY(1,1) NOT NULL, 
NOME VARCHAR(100) NOT NULL,
PRECO NUMERIC(15,2) NOT NULL DEFAULT 0,
CONSTRAINT PK_PRODUTOS PRIMARY KEY(CODIGO));
GO

CREATE TABLE VENDAS (
CODIGO INT IDENTITY(1,1) NOT NULL, 
DATA_ABERTURA DATE NOT NULL,
CLIENTE_CODIGO INT NOT NULL,
VALOR NUMERIC(15,2) NOT NULL,
CONSTRAINT PK_VENDAS PRIMARY KEY (CODIGO),
CONSTRAINT FK1_VENDAS FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTES(CODIGO) ON DELETE NO ACTION ON UPDATE CASCADE );
GO

CREATE TABLE VENDAS_ITENS (
CODIGO INT IDENTITY(1,1) NOT NULL,
ITEM INT NOT NULL,
QUANTIDADE INT NOT NULL DEFAULT 1,
VENDAS_CODIGO INT NOT NULL,
PRODUTOS_CODIGO INT NOT NULL,
PRECO NUMERIC(15,2) NOT NULL DEFAULT 0,
CONSTRAINT PK_VENDAS_ITENS PRIMARY KEY (CODIGO),
CONSTRAINT FK1_VENDAS_ITENS FOREIGN KEY (PRODUTOS_CODIGO) REFERENCES PRODUTOS(CODIGO) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK2_VENDAS_ITENS FOREIGN KEY (VENDAS_CODIGO) REFERENCES VENDAS(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE);
GO